[build]
base = "website/"
command = "mkdocs build --config-file mkdocs.insiders.yml"
publish = "site"

[[headers]]
for = "/*"
[headers.values]
Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''

[[redirects]]
from = "/blog/web3-vision/"
to = "/blog/web3/"
status = 301
force = false

[[redirects]]
from = "/burners/"
to = "/one-dapp-per-key/"
status = 302
force = false

[[redirects]]
from = "/one-dapp-per-key/"
to = "/dapp-keys/"
status = 302
force = false

[[redirects]]
from = "/dev-docs/design/one-dapp-per-key/"
to = "/dev-docs/design/dapp-keys/"
status = 302
force = false
